apiVersion: v1
kind: Pod
metadata:
    labels:
        component: kube-scheduler
        tier: control-plane
    name: kube-scheduler
    namespace: kube-system
spec:
    containers:
        - command:
              - kube-scheduler
              - --authentication-kubeconfig=/etc/kubernetes/scheduler.conf
              - --authorization-kubeconfig=/etc/kubernetes/scheduler.conf
              - --bind-address=0.0.0.0
              - --kubeconfig=/etc/kubernetes/scheduler.conf
              - --leader-elect=true
              - --leader-elect-lease-duration=15s
              - --leader-elect-renew-deadline=10s
              - --port=0
              - --config=/etc/kubernetes/networktraffic-config.yaml
          image: <YOUR_CONTAINER_REGISTRY>/scheduler-plugins/kube-scheduler:<YOUR_TAG>
          imagePullPolicy: Always
          livenessProbe:
              failureThreshold: 8
              httpGet:
                  path: /healthz
                  port: 10259
                  scheme: HTTPS
              initialDelaySeconds: 10
              periodSeconds: 10
              timeoutSeconds: 15
          name: kube-scheduler
          resources:
              requests:
                  cpu: 100m
          startupProbe:
              failureThreshold: 30
              httpGet:
                  path: /healthz
                  port: 10259
                  scheme: HTTPS
              initialDelaySeconds: 10
              periodSeconds: 10
              timeoutSeconds: 15
          volumeMounts:
              - mountPath: /etc/kubernetes/scheduler.conf
                name: kubeconfig
                readOnly: true
              - mountPath: /etc/kubernetes/networktraffic-config.yaml
                name: networktraffic-config
                readOnly: true
    hostNetwork: true
    priorityClassName: system-node-critical
    volumes:
        - hostPath:
              path: /etc/kubernetes/scheduler.conf
              type: FileOrCreate
          name: kubeconfig
        - hostPath:
              path: /etc/kubernetes/networktraffic-config.yaml
              type: File
          name: networktraffic-config
