# create namespace
apiVersion: v1
kind: Namespace
metadata:
    creationTimestamp: null
    name: cs-ns
spec: {}
status: {}

---
# service account
apiVersion: v1
kind: ServiceAccount
metadata:
    creationTimestamp: null
    name: cs-sa
    namespace: cs-ns

---
#  role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    creationTimestamp: null
    name: listpod
    namespace: cs-ns
rules:
    - apiGroups:
          - ""
      resources:
          - pods
      verbs:
          - list
          - get
          - watch

---
# role binding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    creationTimestamp: null
    name: listpodrb
    namespace: cs-ns
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: listpod
subjects:
    - kind: ServiceAccount
      name: cs-sa
      namespace: cs-ns

---
# cluster role
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    creationTimestamp: null
    name: allowlistnode
rules:
    - apiGroups:
          - ""
      resources:
          - nodes
      verbs:
          - list

---
# cluster role binding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    creationTimestamp: null
    name: allowlstnodecrb
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: allowlistnode
subjects:
    - kind: ServiceAccount
      name: default
      namespace: default
---
apiVersion: v1
kind: Pod
metadata:
    creationTimestamp: null
    labels:
        component: kube-scheduler
        tier: control-plane
    name: custom-queue-scheduler
    namespace: kube-system # cs-ns
spec:
    # serviceAccountName: cs-sa
    containers:
        - command:
              - kube-scheduler
              - --bind-address=127.0.0.1
              - --port=10308
              - --secure-port=0
              - --authentication-kubeconfig=/etc/kubernetes/scheduler.conf
              - --authorization-kubeconfig=/etc/kubernetes/scheduler.conf
              - --kubeconfig=/etc/kubernetes/scheduler.conf
              - --leader-elect=false
              - --config=/etc/kubernetes/scheduler-plugin-queue-scheduler.yaml
          image: johanliebert12/sigs.k8s.io-custom-scheduler:0.1.4
          imagePullPolicy: IfNotPresent
          #   livenessProbe:
          #       failureThreshold: 8
          #       httpGet:
          #           path: /healthz
          #           port: 10360
          #           scheme: HTTPS
          #       initialDelaySeconds: 10
          #       periodSeconds: 10
          #       timeoutSeconds: 15
          name: kube-scheduler
          resources:
              requests:
                  cpu: 100m
          #   startupProbe:
          #       failureThreshold: 30
          #       httpGet:
          #           path: /healthz
          #           port: 10360
          #           scheme: HTTPS
          #       initialDelaySeconds: 10
          #       periodSeconds: 10
          #       timeoutSeconds: 15
          volumeMounts:
              - mountPath: /etc/kubernetes/scheduler.conf
                name: kubeconfig
                readOnly: true
              - mountPath: /etc/kubernetes/scheduler-plugin-queue-scheduler.yaml
                name: config
                readOnly: true
    hostNetwork: true
    priorityClassName: system-node-critical
    securityContext:
        seccompProfile:
            type: RuntimeDefault
    volumes:
        - hostPath:
              path: /etc/kubernetes/scheduler.conf
              type: FileOrCreate
          name: kubeconfig
        - hostPath:
              path: /etc/kubernetes/scheduler-plugin-queue-scheduler.yaml
              type: File
          name: config
